Version: 1.0
Slot: 8
Material: BOOK
DisplayName: '#6Profile'
Identifiers:
  6: 443344
Lore:
- '§7Click to open the §b§lShop'
- '§7Click to open the §b§lShop'
- '§7Click to open the §b§lShop'
CommandOnClick:
  - 'profile'
Exclude:
  - 'Lukeo135'
Worlds:
  - 'world_nether'
Sound: BLOCK_CHAIN_PLACE